"""Initial migration

Revision ID: 1e32f8d2ec3e
Revises: 
Create Date: 2025-09-29 18:34:21.111804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e32f8d2ec3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_url', sa.String(length=300), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('number')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('file_url')

    # ### end Alembic commands ###
